language: node_js
node_js: 
    - '11'
install:
  - npm install
script:
  - npm run build
after_script:
  - cd ./dist
  - git init
  - git config user.name "jw"
  - git config user.email "bjfe@qq.com"
  - git add .
  - git commit -m "Update documents"
  - git push --force  "https://${GH_TOKEN}@${GH_REF}" "main:gh-pages"